# Site settings 配置站点
title: 'likemore'
description: 'like it.'
keyword: 'like's blog,like,likemore'
url: 'http://likemore.cc' # your host
baseurl: '/'

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Author 配置博主信息
author: 'likemore'
nickname: 'like'
bio: 'Explorer'
avatar: 'assets/img/like.jpg'

# Search
search: true

# Night mode
nightMode: true

# Comments
disqus: false
disqus_url: ''

# Share
social-share: true
social-share-items: ['weibo', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  weibo: '//weibo.com/likemoreteam'
  github: '//github.com/likemore'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

RSS: false

# Plugins
gems: [jekyll-paginate]